version: "3"

services:
  # App
  test:
    environment:
      - NODE_ENV=testing
    build: .

  app:
    environment:
      - API_HOST=apigs1.wienerdeming.com
    build: .
    image: lab.wienerdeming.com:4567/gs1/gs1_ui
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/gs1_ui
